# Generated by Django 5.1 on 2024-10-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_3E_apart', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Unknown address', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='detail_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='000-0000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
