# Generated by Django 5.1 on 2024-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_3E_apart', '0003_customuser_address_customuser_detail_address_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='사용자가 속한 그룹입니다. 사용자는 각 그룹에서 부여된 모든 권한을 얻습니다.', related_name='customuser_set', to='auth.group', verbose_name='그룹'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='이 사용자에 대한 특정 권한입니다.', related_name='customuser_set', to='auth.permission', verbose_name='사용자 권한'),
        ),
    ]
