# Generated by Django 5.1 on 2024-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_3E_apart', '0006_dislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
